trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
    - job: Firstjob
      steps:
      - bash: echo Build FirstJob
    - job: Secondjob
      steps:
      - bash: echo Build SecondtJob
 - stage: DevDeploy
   jobs:
    - job: DevDeploy
      steps:
      - bash: echo Build DevDeploy
 - stage: QaDeploy
   jobs:
    - job: QaDeploy
      steps:
      - bash: echo Build QaDeploy
 - stage: ProdDeploy
   jobs:
   - job: ProdDeploy
     steps:
     - bash: echo Build ProdDeploy