trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
    - job: Firstjobp
      steps:
      - bash: echo Build FirstJob
      - bash: echo $(PilelineLevelVariable)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourceDirectory)
      - bash: echo $(System.DefaulsWorkingDirectory)
      - bash: ls -r $(System.DefaulsWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: echo java -version
      - bash: echo node --version
      - bash: echo python --version
      - bash: echo mv -version
    # - job: Secondjob
    #   steps:
    #   - bash: echo Build SecondtJob
    #   - bash: echo $(PilelineLevelVariable)
    
#  - stage: DevDeploy
#    variables:
#      environment: Dev
#    dependsOn: Build
#    jobs:
#     - job: DevDeploy
#       steps:
#       - bash: echo $(PilelineLevelVariable) Dev Deploy job
#  - stage: QaDeploy
#    variables:
#      environment: QA
#    dependsOn: Build
#    jobs:
#     - job: QaDeploy
#       steps:
#       - bash: echo $(PilelineLevelVariable) QaDeploy
#  - stage: ProdDeploy
#    variables:
#      environment: Prod
#    dependsOn:
#    - DevDeploy
#    - QaDeploy
#    jobs:
#    - job: ProdDeploy
#      steps:
#      - bash: echo $(PilelineLevelVariable) ProdDeploy