trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
    - job: Firstjob
      steps:
      - bash: echo Build FirstJob
    - job: Secondjob
      steps:
      - bash: echo Build SecondtJob
      - bash: echo $(PilelineLevelVariable)
 - stage: DevDeploy
   variables:
     environment: Dev
   dependsOn: Build
   jobs:
    - job: DevDeploy
      steps:
      - bash: echo $(PilelineLevelVariable) Dev Deploy job
 - stage: QaDeploy
   dependsOn: Build
   jobs:
    - job: QaDeploy
      steps:
      - bash: echo $(PilelineLevelVariable) QaDeploy
 - stage: ProdDeploy
   dependsOn:
   - DevDeploy
   - QaDeploy
   jobs:
   - job: ProdDeploy
     steps:
     - bash: echo $(PilelineLevelVariable) ProdDeploy