trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    command: login
    containerRegistry: 'kuldeepazad15-docker-hub'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImags: 'Ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build an Image
        inputs:
          containerRegistry: 'kuldeepazad15-docker-hub'
          repository: 'kuldeepazad15/currency-exchange-devops'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourceDirectory)/Dockerfile'
          tags: '$(tag)'